<a href="https://colab.research.google.com/github/dhivya4/Inceptz/blob/main/Drug200.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/balaji2v/Inceptez_Batch19/main/drug200.csv")

In [6]:
df.describe(include='all').T

count unique    top freq       mean        std    min      25%  \
Age          200.0    NaN    NaN  NaN     44.315  16.544315   15.0     31.0   
Sex            200      2      M  104        NaN        NaN    NaN      NaN   
BP             200      3   HIGH   77        NaN        NaN    NaN      NaN   
Cholesterol    200      2   HIGH  103        NaN        NaN    NaN      NaN   
Na_to_K      200.0    NaN    NaN  NaN  16.084485   7.223956  6.269  10.4455   
Drug           200      5  DrugY   91        NaN        NaN    NaN      NaN   

                 50%    75%     max  
Age             45.0   58.0    74.0  
Sex              NaN    NaN     NaN  
BP               NaN    NaN     NaN  
Cholesterol      NaN    NaN     NaN  
Na_to_K      13.9365  19.38  38.247  
Drug             NaN    NaN     NaN

In [4]:
df.shape

(200, 6)

In [5]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [7]:
for var in df.columns:
    
    print(df[var].value_counts())

47    8
23    7
28    7
49    7
39    6
32    6
50    5
37    5
58    5
60    5
22    5
34    4
72    4
51    4
42    4
26    4
24    4
74    4
67    4
68    4
61    4
56    4
20    4
36    4
45    4
41    4
31    4
43    4
65    4
57    4
53    3
40    3
70    3
59    3
16    3
38    3
15    3
69    3
35    3
18    3
64    3
52    2
55    2
62    2
19    2
29    2
66    2
73    2
46    2
48    2
54    1
17    1
33    1
63    1
30    1
21    1
25    1
Name: Age, dtype: int64
M    104
F     96
Name: Sex, dtype: int64
HIGH      77
LOW       64
NORMAL    59
Name: BP, dtype: int64
HIGH      103
NORMAL     97
Name: Cholesterol, dtype: int64
12.006    2
18.295    2
25.355    1
11.939    1
16.347    1
         ..
24.658    1
24.276    1
13.967    1
19.675    1
11.349    1
Name: Na_to_K, Length: 198, dtype: int64
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [13]:
df.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [28]:
cols = ['Sex','BP','Cholesterol','Drug']

In [29]:
from sklearn.preprocessing import LabelEncoder
df[cols] = df[cols].apply(LabelEncoder().fit_transform)

In [30]:
X = df[['Age','Sex','BP','Cholesterol','Na_to_K']]
Y = df[['Drug']]

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [32]:
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

In [33]:
X_train_scaler = sc.fit(X_train)
X_train_trans_scaler = sc.fit_transform(X_train)

In [34]:
X_train_trans_scaler

array([[ 1.39698536,  0.93094934,  1.41004   ,  1.1055416 , -1.20952998],
       [-1.6008373 ,  0.93094934,  1.41004   ,  1.1055416 , -0.79159284],
       [-1.48092439, -1.07417231, -1.08876506, -0.90453403, -0.11244499],
       [ 0.37772565,  0.93094934,  1.41004   ,  1.1055416 ,  0.32290619],
       [-0.04196952,  0.93094934, -1.08876506, -0.90453403,  0.04428143],
       [-1.30105503, -1.07417231,  1.41004   , -0.90453403, -1.4359126 ],
       [-0.52162114,  0.93094934,  1.41004   ,  1.1055416 , -1.52298283],
       [-0.40170824,  0.93094934,  0.16063747,  1.1055416 , -1.34884236],
       [-1.24109858,  0.93094934,  1.41004   , -0.90453403,  1.55930356],
       [-0.88135986,  0.93094934, -1.08876506, -0.90453403, -0.26917142],
       [ 1.45694181, -1.07417231, -1.08876506,  1.1055416 , -0.94831927],
       [ 0.1978563 , -1.07417231,  0.16063747, -0.90453403, -1.01797546],
       [-0.46166469, -1.07417231, -1.08876506,  1.1055416 ,  0.2880781 ],
       [ 0.91733373, -1.07417231,  0.1

In [35]:
X_train_trans_scaler.size

700

In [37]:
X_test_trans_scaler = sc.transform(X_test)

X_test_trans_scaler.size

300

In [38]:
gnb = GaussianNB()
knn = KNeighborsClassifier()

In [42]:
#fitting models and checking for classification metrics
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)
for i in [gnb,knn]:
  i.fit(X_train,Y_train)
  pred = i.predict(X_test)
  test_score = accuracy_score(Y_test,pred)
  train_score = accuracy_score(Y_train,i.predict(X_train))
  print(i)
  print('Accuracy score for train data', accuracy_score(Y_test,pred))
  print('Accuracy score for test data', accuracy_score(Y_train,i.predict(X_train)))
  print(classification_report(Y_test,pred))
  print(confusion_matrix(Y_test,pred))


GaussianNB()
Accuracy score for train data 0.8
Accuracy score for test data 0.8285714285714286
              precision    recall  f1-score   support

           0       1.00      0.59      0.74        27
           1       0.50      1.00      0.67         4
           2       0.62      0.83      0.71         6
           3       0.44      1.00      0.62         4
           4       1.00      1.00      1.00        19

    accuracy                           0.80        60
   macro avg       0.71      0.89      0.75        60
weighted avg       0.89      0.80      0.81        60

[[16  3  3  5  0]
 [ 0  4  0  0  0]
 [ 0  1  5  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 19]]
KNeighborsClassifier()
Accuracy score for train data 0.5166666666666667
Accuracy score for test data 0.7642857142857142
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       0.10      0.25      0.14         4
           2       0.00      0.00      0.0

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
