In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report


In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/balaji2v/Inceptez_Batch19/main/teleCust1000t.csv")

In [6]:
df.shape

(1000, 12)

In [7]:
df.describe(include='all').T

count    mean         std   min   25%   50%   75%     max
region   1000.0   2.022    0.816200   1.0   1.0   2.0   3.0     3.0
tenure   1000.0  35.526   21.359812   1.0  17.0  34.0  54.0    72.0
age      1000.0  41.684   12.558816  18.0  32.0  40.0  51.0    77.0
marital  1000.0   0.495    0.500225   0.0   0.0   0.0   1.0     1.0
address  1000.0  11.551   10.086681   0.0   3.0   9.0  18.0    55.0
income   1000.0  77.535  107.044165   9.0  29.0  47.0  83.0  1668.0
ed       1000.0   2.671    1.222397   1.0   2.0   3.0   4.0     5.0
employ   1000.0  10.987   10.082087   0.0   3.0   8.0  17.0    47.0
retire   1000.0   0.047    0.211745   0.0   0.0   0.0   0.0     1.0
gender   1000.0   0.517    0.499961   0.0   0.0   1.0   1.0     1.0
reside   1000.0   2.331    1.435793   1.0   1.0   2.0   3.0     8.0
custcat  1000.0   2.487    1.120306   1.0   1.0   3.0   3.0     4.0

In [8]:
X = df.iloc[:,:-1]
print(X)

     region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9    64.0   4       5     0.0   
1         3      11   33        1        7   136.0   5       5     0.0   
2         3      68   52        1       24   116.0   1      29     0.0   
3         2      33   33        0       12    33.0   2       0     0.0   
4         2      23   30        1        9    30.0   1       2     0.0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0    27.0   3       0     0.0   
996       1       7   34        0        2    22.0   5       5     0.0   
997       3      67   59        0       40   944.0   5      33     0.0   
998       3      70   49        0       18    87.0   2      22     0.0   
999       3      50   36        1        7    39.0   3       3     0.0   

     gender  reside  
0         0       2  
1         0       6  
2         1       2  
3         1       1  
4

In [9]:
Y = df.iloc[:,-1]
print(Y)

0      1
1      4
2      3
3      1
4      3
      ..
995    1
996    1
997    4
998    3
999    2
Name: custcat, Length: 1000, dtype: int64


In [10]:
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

In [11]:
standard_scaler = StandardScaler()

In [23]:
X_train_scaler = standard_scaler.fit(X_train)
X_train_trans_scaler = standard_scaler.fit_transform(X_train)


X_train_scaler

StandardScaler()

In [24]:
X_train_trans_scaler.size

7700

In [13]:
X_test_trans_scaler = standard_scaler.transform(X_test)

X_test_trans_scaler.size


3300

In [14]:
model= KNeighborsClassifier()

In [15]:
model.fit(X_train,Y_train)

KNeighborsClassifier()

In [16]:
Y_pred = model.predict(X_test)
Z_pred = model.predict(X_train)

In [17]:
acc_score = accuracy_score(Y_test, Y_pred)
print(acc_score)

0.35


In [18]:
acc_score = accuracy_score(Y_test, Y_pred)

In [19]:
print(confusion_matrix(Y_test, Y_pred))

[[44 16 20 10]
 [13 19 18  9]
 [21 21 30  8]
 [27 17 15 12]]


In [20]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           1       0.42      0.49      0.45        90
           2       0.26      0.32      0.29        59
           3       0.36      0.38      0.37        80
           4       0.31      0.17      0.22        71

    accuracy                           0.35       300
   macro avg       0.34      0.34      0.33       300
weighted avg       0.35      0.35      0.34       300



In [21]:
def knn_model(k, X_train, X_test, Y_train, Y_test, weights='uniform', metric='minkowski'):
    # weights: uniform, distance ; metric: minkowski, euclidean, manhattan, cosine
    knn = KNeighborsClassifier(n_neighbors = k, weights=weights, metric=metric)
    print("Weights :", weights)
    print("Metric : ", metric)
   


In [27]:
   knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [31]:
Y_pred_test = knn.predict(X_test)

In [32]:
Y_pred_test

array([1, 1, 1, 1, 3, 1, 2, 2, 4, 1, 3, 4, 2, 1, 1, 3, 1, 1, 1, 1, 2, 2,
       1, 3, 2, 1, 1, 2, 3, 4, 1, 3, 2, 3, 3, 1, 3, 1, 2, 3, 1, 2, 1, 4,
       1, 1, 3, 1, 1, 1, 4, 3, 3, 1, 3, 1, 3, 1, 1, 4, 3, 2, 1, 2, 2, 1,
       4, 1, 4, 2, 4, 3, 3, 3, 3, 3, 1, 3, 2, 2, 2, 3, 1, 1, 2, 3, 3, 1,
       1, 3, 1, 2, 1, 3, 3, 3, 3, 4, 2, 4, 3, 3, 3, 1, 1, 2, 3, 1, 3, 2,
       3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 2, 4, 3, 1, 2, 2, 4, 2, 3, 1, 2, 3,
       1, 2, 3, 3, 1, 1, 2, 3, 3, 2, 1, 2, 2, 4, 2, 2, 2, 3, 1, 4, 3, 2,
       2, 1, 4, 2, 1, 1, 3, 1, 2, 2, 1, 4, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       4, 1, 3, 4, 3, 2, 2, 2, 1, 1, 4, 3, 2, 1, 3, 1, 1, 2, 3, 4, 1, 4,
       1, 3, 2, 1, 1, 2, 3, 2, 4, 3, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1,
       1, 4, 1, 1, 1, 1, 1, 2, 4, 4, 3, 4, 3, 3, 3, 3, 2, 4, 1, 2, 4, 2,
       2, 3, 2, 4, 1, 1, 1, 2, 4, 2, 3, 2, 1, 1, 3, 2, 1, 2, 1, 3, 2, 3,
       1, 3, 2, 2, 2, 3, 1, 1, 4, 3, 4, 3, 3, 4, 1, 2, 3, 3, 3, 2, 3, 3,
       3, 4, 4, 4, 3, 4, 1, 2, 1, 2, 2, 3, 3, 4], d

In [33]:
Y_pred_train = knn.predict(X_train)

In [34]:
Y_pred_train

array([2, 4, 4, 2, 1, 1, 2, 3, 2, 2, 3, 1, 4, 3, 1, 1, 3, 3, 3, 4, 3, 1,
       2, 2, 1, 2, 2, 3, 3, 1, 1, 2, 3, 3, 2, 4, 3, 3, 3, 2, 2, 1, 2, 1,
       3, 1, 3, 3, 3, 3, 2, 2, 2, 3, 2, 1, 1, 3, 3, 3, 1, 3, 2, 2, 2, 1,
       3, 4, 4, 4, 2, 2, 1, 1, 1, 1, 1, 3, 1, 4, 4, 1, 4, 2, 4, 1, 1, 1,
       1, 3, 4, 1, 4, 2, 1, 4, 1, 2, 2, 1, 3, 2, 2, 2, 1, 2, 3, 3, 2, 3,
       1, 1, 4, 2, 1, 3, 2, 1, 4, 1, 3, 2, 4, 1, 2, 1, 4, 2, 4, 1, 2, 3,
       3, 1, 1, 1, 1, 2, 2, 1, 1, 1, 4, 3, 1, 4, 1, 3, 3, 4, 3, 3, 1, 3,
       2, 2, 2, 1, 2, 1, 1, 1, 1, 3, 1, 4, 3, 3, 3, 2, 3, 4, 3, 2, 3, 3,
       2, 1, 3, 2, 3, 1, 2, 1, 4, 3, 3, 3, 1, 3, 2, 3, 1, 3, 1, 4, 2, 4,
       3, 4, 2, 1, 3, 2, 3, 1, 3, 1, 3, 3, 3, 3, 2, 1, 4, 1, 4, 2, 1, 2,
       2, 3, 1, 3, 3, 1, 2, 1, 2, 3, 1, 3, 1, 2, 3, 1, 1, 4, 1, 4, 1, 3,
       3, 3, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 3, 3, 1, 3, 2, 3, 1, 3, 2, 1,
       1, 4, 3, 3, 2, 3, 3, 2, 4, 1, 3, 4, 3, 2, 2, 3, 2, 1, 2, 1, 1, 2,
       3, 3, 3, 1, 3, 1, 3, 3, 3, 1, 1, 2, 1, 2, 2,

In [35]:
accuracy_score(Y_pred_train,Y_train)

0.5214285714285715

In [36]:
accuracy_score(Y_pred_test,Y_test)

0.35

In [37]:
precision_score(Y_pred_test, Y_test, average='weighted')

0.3751945240179306

In [38]:
precision_score(Y_pred_train, Y_train, average='weighted')

0.5657108322435169

In [39]:
confusion_matrix(Y_pred_train, Y_train)

array([[122,  27,  48,  49],
       [ 13,  91,  43,  32],
       [ 29,  26, 102,  34],
       [ 12,  14,   8,  50]], dtype=int64)

In [40]:
confusion_matrix(Y_pred_test, Y_test)

array([[44, 13, 21, 27],
       [16, 19, 21, 17],
       [20, 18, 30, 15],
       [10,  9,  8, 12]], dtype=int64)

In [41]:
print(classification_report(Y_pred_train, Y_train))

              precision    recall  f1-score   support

           1       0.69      0.50      0.58       246
           2       0.58      0.51      0.54       179
           3       0.51      0.53      0.52       191
           4       0.30      0.60      0.40        84

    accuracy                           0.52       700
   macro avg       0.52      0.53      0.51       700
weighted avg       0.57      0.52      0.53       700



In [42]:
print(classification_report(Y_pred_test, Y_test))

              precision    recall  f1-score   support

           1       0.49      0.42      0.45       105
           2       0.32      0.26      0.29        73
           3       0.38      0.36      0.37        83
           4       0.17      0.31      0.22        39

    accuracy                           0.35       300
   macro avg       0.34      0.34      0.33       300
weighted avg       0.38      0.35      0.36       300

