In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score, precision_score,confusion_matrix, classification_report

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/naga-sk/DataScienceTraining-Assignments/main/naive_bayes/purchase.csv")

In [4]:
df.head(5)

Day Discount Free Delivery Purchase
0  Holiday       No            No       No
1  Holiday       No            No       No
2  Holiday       No            No       No
3  Weekday       No            No       No
4  Weekday       No           Yes       No

In [5]:
df.shape

(30, 4)

In [6]:
df.describe(include='all').T

count unique      top freq
Day              30      3  Holiday   11
Discount         30      2      Yes   20
Free Delivery    30      2      Yes   23
Purchase         30      2      Yes   24

In [7]:
df.dtypes

Day              object
Discount         object
Free Delivery    object
Purchase         object
dtype: object

In [8]:
cols = ['Day','Discount','Free Delivery','Purchase']

In [9]:
#label encoding the data
from sklearn.preprocessing import LabelEncoder
df[cols] = df[cols].apply(LabelEncoder().fit_transform)

In [10]:
df.head()

Day  Discount  Free Delivery  Purchase
0    0         0              0         0
1    0         0              0         0
2    0         0              0         0
3    1         0              0         0
4    1         0              1         0

In [11]:
X = df.iloc[:,:-1]

In [12]:
Y = df.iloc[:,-1]

In [13]:
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

 model = multinomialnb()

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
model = MultinomialNB()

In [16]:
X_train.head()

Day  Discount  Free Delivery
22    1         1              1
23    2         1              0
4     1         0              1
2     0         0              0
25    2         1              1

In [17]:
X_test.head()

Day  Discount  Free Delivery
17    1         1              1
21    1         1              1
10    0         1              1
19    1         1              1
14    1         0              1

In [18]:
Y_train.head()

22    1
23    1
4     0
2     0
25    1
Name: Purchase, dtype: int32

In [19]:
Y_test.head()

17    1
21    1
10    1
19    1
14    1
Name: Purchase, dtype: int32

In [20]:
X_train.value_counts()

Day  Discount  Free Delivery
0    0         0                4
     1         1                4
1    1         1                4
2    1         1                4
0    0         1                2
2    1         0                2
1    0         1                1
dtype: int64

In [21]:
X_test.value_counts()

Day  Discount  Free Delivery
1    1         1                4
0    1         1                1
1    0         0                1
               1                1
2    0         1                1
     1         1                1
dtype: int64

In [23]:
Y_train.value_counts()

1    16
0     5
Name: Purchase, dtype: int64

In [24]:
Y_test.value_counts()

1    8
0    1
Name: Purchase, dtype: int64

In [26]:
model.fit(X_train, Y_train)

MultinomialNB()

In [30]:
Y_pred_train = model.predict(X_train)

In [31]:
Y_pred_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [32]:
Y_pred_test = model.predict(X_test)

In [33]:
Y_pred_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
accuracy_score(Y_pred_train, Y_train)

0.7619047619047619

In [39]:
precision_score(Y_pred_test, Y_test)

1.0

In [41]:
accuracy_score(Y_pred_test,Y_test)

0.8888888888888888

In [42]:
confusion_matrix(Y_pred_train, Y_train)

array([[ 0,  0],
       [ 5, 16]], dtype=int64)

In [45]:
confusion_matrix(Y_pred_test, Y_test)

array([[0, 0],
       [1, 8]], dtype=int64)

In [46]:
print(classification_report(Y_pred_train, Y_train))
print(classification_report(Y_pred_test, Y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.76      0.86        21

    accuracy                           0.76        21
   macro avg       0.50      0.38      0.43        21
weighted avg       1.00      0.76      0.86        21

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.89      0.94         9

    accuracy                           0.89         9
   macro avg       0.50      0.44      0.47         9
weighted avg       1.00      0.89      0.94         9



C:\Users\varadharajan B\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\varadharajan B\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\varadharajan B\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\varadharajan B\anaconda3\lib\site-packages\