In [ ]:
import numpy as np
np.version.version

'1.21.6'

In [ ]:
type(a)
a.shape
len(a)

10

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a.dtype)
a = a.astype(np.float64)
print(a.dtype)


int64
float64


In [ ]:
b = a.reshape((2,5))
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [ ]:
x = np.zeros(10)
print(x)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
y = np.array(range(10,49))
print(y)
z = y[::-1]
print(z)
# DataInvaders

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
A = np.array([[1,2,3],[4,5,6]])

In [ ]:
x= np.array(range(0,8))
D = x.reshape(3,3)
print(D)

ValueError: ignored

In [ ]:
x = np.array([1,2,0,0,4,0])
x = np.where(x!=0)[0]
print(x)



[0 1 4]


In [ ]:
I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
R = np.random.random((3,3,3))
print(R)

[[[0.01664903 0.70738312 0.47622771]
  [0.98471433 0.54594205 0.74338646]
  [0.14568449 0.79197299 0.84603612]]

 [[0.94775319 0.46145994 0.36591043]
  [0.28653458 0.46443274 0.71817867]
  [0.82825522 0.27517543 0.5682425 ]]

 [[0.71439412 0.8302378  0.56695116]
  [0.81813637 0.2872371  0.56682442]
  [0.08271323 0.67571917 0.89198793]]]


In [ ]:
R = np.random.random((10,10))
Min = R.min()
Max = R.max()
print(Min)
print(Max)
 

0.00021849120240780007
0.9887541041757211


In [ ]:
R = np.random.random(30)
Mean = R.mean()
print(Mean)

0.5368060493309301


In [ ]:
X = np.ones((2,2))
print(X)
Brd = np.pad(X, pad_width=1, mode='constant', constant_values=0)
print(Brd)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False